x-logging:
  &logging
  logging:
    options:
      max-file: '3'
      compress: 'false'
      max-size: '100m'

services:
  mina:
    image: minaprotocol/mina-daemon:${MINA_VERSION}
    container_name: mina
    environment:
      MINA_PUBLIC_KEY: ${MINA_PUBLIC_KEY}
      MINA_PRIVKEY_PASS: ${MINA_PASS}
      UPTIME_PRIVKEY_PASS: ${MINA_PASS}
    command: |
      daemon
      --uptime-submitter-key /keys/${WALLET_NAME}
      --uptime-url https://uptime-backend.minaprotocol.com/v1/submit
      --block-producer-key /keys/${WALLET_NAME}
      --coinbase-receiver ${CB_RECIEVER}
      --minimum-block-reward 720
      --file-log-level Debug
      --log-level Info
      --peer-list-url ${PEER_LIST_URL}
    volumes:
      - ./keys:/keys:ro
      - ./.mina-config:/root/.mina-config
    ports:
      - "8302:8302"
      - "6060:6060"
    restart: always
    <<: *logging
