x-logging:
  &logging
  logging:
    options:
      max-file: '3'
      compress: 'false'
      max-size: '100m'

services:
  mina:
    image: minaprotocol/mina-daemon:${MINA_VERSION}
    container_name: mina
    environment:
      MINA_PUBLIC_KEY: ${MINA_PUBLIC_KEY}
      MINA_PRIVKEY_PASS: ${MINA_PASS}
      UPTIME_PRIVKEY_PASS: ${MINA_PASS}
      CB_RECIEVER: ${CB_RECIEVER}
      WALLET_NAME: ${WALLET_NAME}
      PEER_LIST_URL: ${PEER_LIST_URL}
    command: |
       daemon
       --uptime-submitter-key /keys/${WALLET_NAME}
       --uptime-url https://uptime-backend.minaprotocol.com/v1/submit
       --block-producer-key /keys/${WALLET_NAME}
       --coinbase-receiver ${CB_RECIEVER}
       #--open-limited-graphql-port
       #--limited-graphql-port 3095
       --minimum-block-reward 720
       #--insecure-rest-server
       --file-log-level Debug
       --log-level Info
       --peer-list-url ${PEER_LIST_URL}
    volumes:
      - ./keys:/keys:ro
      - ./.mina-config:/root/.mina-config
    ports:
      - "8302:8302"
      - "6060:6060"
    restart: unless-stopped
    <<: *logging
